# CMake generated Testfile for 
# Source directory: /Users/suprathps/code/Wire
# Build directory: /Users/suprathps/code/Wire/build-native
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("ChaCha20PRNGTest" "/Users/suprathps/code/Wire/build-native/test_chacha20_prng")
set_tests_properties("ChaCha20PRNGTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;95;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("PRNGSecurityAndPerfTest" "/Users/suprathps/code/Wire/build-native/test_prng_security_and_perf")
set_tests_properties("PRNGSecurityAndPerfTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;99;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("KnockEngineTest" "/Users/suprathps/code/Wire/build-native/test_knock_engine")
set_tests_properties("KnockEngineTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;103;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("TLSMimicryTest" "/Users/suprathps/code/Wire/build-native/test_tls_mimicry")
set_tests_properties("TLSMimicryTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;107;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("DiscoveryEngineTest" "/Users/suprathps/code/Wire/build-native/test_discovery_engine")
set_tests_properties("DiscoveryEngineTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;111;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("DoubleRatchetTest" "/Users/suprathps/code/Wire/build-native/test_double_ratchet")
set_tests_properties("DoubleRatchetTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;115;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("MerkleDAGTest" "/Users/suprathps/code/Wire/build-native/test_merkle_dag")
set_tests_properties("MerkleDAGTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;119;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("CapabilitySeveringTest" "/Users/suprathps/code/Wire/build-native/test_capability_severing")
set_tests_properties("CapabilitySeveringTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;123;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("GenesisManagerTest" "/Users/suprathps/code/Wire/build-native/test_genesis_manager")
set_tests_properties("GenesisManagerTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;127;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("VirtioSerialBridgeTest" "/Users/suprathps/code/Wire/build-native/test_virtio_serial_bridge")
set_tests_properties("VirtioSerialBridgeTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;131;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("TerminalUITest" "/Users/suprathps/code/Wire/build-native/test_terminal_ui")
set_tests_properties("TerminalUITest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;135;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("UTF8SpecialCharsTest" "/Users/suprathps/code/Wire/build-native/test_utf8_special_chars")
set_tests_properties("UTF8SpecialCharsTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;139;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("ContactManagerTest" "/Users/suprathps/code/Wire/build-native/test_contact_manager")
set_tests_properties("ContactManagerTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;143;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("UpdateManagerTest" "/Users/suprathps/code/Wire/build-native/test_update_manager")
set_tests_properties("UpdateManagerTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;147;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("PortableUSBModeTest" "/Users/suprathps/code/Wire/build-native/test_portable_usb_mode")
set_tests_properties("PortableUSBModeTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;151;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("iMessageTUITest" "/Users/suprathps/code/Wire/build-native/test_imessage_tui")
set_tests_properties("iMessageTUITest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;155;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
add_test("RealSocketTransportTest" "/Users/suprathps/code/Wire/build-native/test_real_socket_transport")
set_tests_properties("RealSocketTransportTest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/suprathps/code/Wire/CMakeLists.txt;159;add_test;/Users/suprathps/code/Wire/CMakeLists.txt;0;")
