/**
 * @file knock_engine.hpp
 * @brief 3-Packet Mathematical Knock Burst Generator and Cryptographic Validator
 * @project Project Wire
 * 
 * @details
 * Implements the "Mathematical Knock" payload structure, deterministic packet length calculation,
 * and 1280-byte padded payload authentication.
 * 
 * Knock Protocol Spec:
 * - Burst Count: 3 UDP packets per knock sequence.
 * - Dynamic Packet Length: Length_n = 64 + (HMAC_mod(Seed, Epoch, Packet_Index) % 1024).
 * - Fixed Padded Transmission: Frame is padded to 1280 bytes (IPv6 Minimum MTU).
 * - Replay Protection: 64-bit Monotonic Counter + Timestamp verification window (+/- 30 seconds).
 */

#ifndef WIRE_KNOCK_ENGINE_HPP
#define WIRE_KNOCK_ENGINE_HPP

#include <cstdint>
#include <cstddef>
#include <array>
#include <vector>
#include <optional>
#include "chacha20_prng.hpp"

namespace wire::crypto {

static constexpr size_t KNOCK_MTU_PADDING_SIZE = 1280;
static constexpr size_t KNOCK_BURST_COUNT = 3;

/**
 * @struct KnockPacket
 * @brief Represents a single mathematical knock packet payload.
 */
struct KnockPacket {
    uint8_t packet_index;                  /**< Index in 3-packet sequence (0, 1, 2) */
    uint64_t epoch;                        /**< Epoch timestamp index */
    uint64_t monotonic_counter;            /**< Anti-replay monotonic sequence counter */
    std::array<uint8_t, 32> sender_pubkey; /**< Sender's static identity public key */
    std::array<uint8_t, 16> mac_tag;       /**< 128-bit authentication MAC tag */
    std::vector<uint8_t> payload_data;     /**< 1280-byte padded payload */

    /**
     * @brief Formats packet into a 1280-byte wire buffer.
     * @return std::array<uint8_t, 1280> Padded network buffer.
     */
    [[nodiscard]] std::array<uint8_t, KNOCK_MTU_PADDING_SIZE> serialize() const noexcept;
};

/**
 * @class KnockEngine
 * @brief Handles generation and validation of 3-packet mathematical knock bursts.
 */
class KnockEngine {
public:
    /**
     * @brief Calculates deterministic packet length for packet index `n` in epoch.
     * Formula: Length_n = 64 + (HMAC_derive(Knock_Key, Index) % 1024)
     * @param knock_key 256-bit knock key from PRNG.
     * @param packet_index Index (0..2).
     * @return uint16_t Dynamic packet payload length.
     */
    [[nodiscard]] static uint16_t calculate_knock_length(const std::array<uint8_t, 32>& knock_key, uint8_t packet_index) noexcept;

    /**
     * @brief Generates a 3-packet knock sequence for an epoch target.
     * @param target EpochTarget generated by ChaCha20PRNG.
     * @param sender_pubkey Sender's public identity key.
     * @param counter Monotonic sequence number.
     * @return std::array<KnockPacket, 3> Array of 3 formatted knock packets.
     */
    [[nodiscard]] static std::array<KnockPacket, KNOCK_BURST_COUNT> generate_knock_burst(
        const EpochTarget& target,
        const std::array<uint8_t, 32>& sender_pubkey,
        uint64_t counter) noexcept;

    /**
     * @brief Validates an incoming knock packet MAC tag and timestamp.
     * @param buffer 1280-byte raw network buffer received.
     * @param knock_key Expected knock key for current/adjacent epoch.
     * @param current_counter Current expected minimum sequence counter.
     * @return std::optional<KnockPacket> Decrypted packet if valid MAC tag, nullopt if invalid.
     */
    [[nodiscard]] static std::optional<KnockPacket> validate_knock_packet(
        const std::array<uint8_t, KNOCK_MTU_PADDING_SIZE>& buffer,
        const std::array<uint8_t, 32>& knock_key,
        uint64_t current_counter) noexcept;
};

} // namespace wire::crypto

#endif // WIRE_KNOCK_ENGINE_HPP
